name: Rails

on: [push]

env:
  IMAGE_NAME: ghcr.io/ahastudio/rails:6.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io --username $USERNAME --password-stdin
        env:
          USERNAME: ahastudio
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd rails
          docker build -t rails .

      - name: Push Docker image (latest)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag rails $IMAGE_NAME
          docker push $IMAGE_NAME
